# This is a config for E2B sandbox template.
# You can use template ID (qaj71gb5qk4pj791vx0n) or template name (vibe-nextjs-ramatya34) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-ramatya34") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-ramatya34") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-ramatya34')

team_id = "0ce1c989-9c12-4fc1-8d2e-521da28c01cf"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-ramatya34"
template_id = "qaj71gb5qk4pj791vx0n"
